export const ACTION_TYPE = {
	SET_USER: 'SET_USER',
	LOGOUT: 'LOGOUT',
	ADD_PRODUCT: 'ADD_PRODUCT',
	SET_PRODUCTS: 'SET_PRODUCTS',
	SET_PRODUCT: 'SET_PRODUCT',
	DELETE_PRODUCT: 'DELETE_PRODUCT',
	UPDATE_PRODUCT: 'UPDATE_PRODUCT',
	ADD_TO_CART: 'ADD_TO_CART',
	REMOVE_FROM_CART: 'REMOVE_FROM_CART',
	CHANGE_CART_COUNT: 'CHANGE_CART_COUNT',
	SET_LOADING: 'SET_LOADING',
};
